[add] Switching talk on event page
tegehoge/LeacTion pull request #12
Opened 2020-10-08 03:16 UTC by tomoeine

## Issue
https://github.com/tegehoge/LeacTion/issues/5

## やったこと
イベントページに、発表切り替えセレクトボックスを追加した

## 見てほしいこと
全体的にコードと仕様のレビューをお願いします🙇‍♀️
デザインは後からあてる前提で、超適当です・・・（我ながら分かりづらいと思っている）

2020-10-08 08:30 UTC, mather requested changes
レビューしました。
Vue3と仕様に関してはバッチリだと思います！

2020-10-08 08:30 UTC, mather commented on src/pages/Event.vue
> +        </select>
`talk` が異なる文脈で２つ出てきておりシャドーイングになってます。
現在選択されている発表を `currentTalk` などのようにしてわかりやすくしてはどうでしょうか？

2020-10-08 08:30 UTC, mather commented on src/pages/Event.vue
> +          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
`h-6 w-6` くらいに大きくしてもいいかも？

2020-10-08 08:30 UTC, mather commented on src/pages/Event.vue
> +        <select class="w-full block appearance-none border-2 rounded p-2" v-model="talk">
`label.for` に対応する `id` 属性があるといいです。

2020-10-11 09:34 UTC, tomoeine commented on src/pages/Event.vue
> +          for="external_url"
うあ、コピペしたままでした😅
https://github.com/tegehoge/LeacTion/pull/12/commits/55318e33e929cecc85fb5f45adbcb83bac874c39 で直しました”

2020-10-11 09:35 UTC, tomoeine commented on src/pages/Event.vue
> +        <select class="w-full block appearance-none border-2 rounded p-2" v-model="talk">
https://github.com/tegehoge/LeacTion/pull/12/commits/55318e33e929cecc85fb5f45adbcb83bac874c39 で直しました！

2020-10-11 09:35 UTC, tomoeine commented on src/pages/Event.vue
> +          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
https://github.com/tegehoge/LeacTion/pull/12/commits/b8d12f751605b14e24eb0af3cde4d8f9ac9d3c1c でやってみました！

2020-10-11 09:35 UTC, tomoeine commented on src/pages/Event.vue
> +        </select>
確かに＞＜
https://github.com/tegehoge/LeacTion/pull/12/commits/665d679c9b09b4697db228670debf394c5e66c27 で修正しました！

2020-10-11 10:01 UTC, mather approved these changes
LGTM

2020-10-11 10:02 UTC, merged