コメント削除機能
tegehoge/LeacTion pull request #34
Opened 2020-11-05 16:33 UTC by koogawa

#10 の対応です。

実装中

2020-11-05 16:35 UTC, koogawa commented
> 削除リクエストにコメントIDとハッシュ化前のユーザーIDを送るようにすれば、確実に自分のブラウザからコメントを削除していることが判別できそう

これ良さそうですね！

@mather この判別をソースコードのどのあたりでやるべきか迷っています！

2020-11-05 16:35 UTC, koogawa commented
コメント削除まではできました

2020-11-05 16:36 UTC, koogawa commented on functions/src/index.ts
> +  // const likeReq = req.body as CommentLikeRequest;
このへんで コメントIDとユーザーIDを比較する？

2020-11-05 16:37 UTC, koogawa commented on src/components/CommentBlock.vue
> +      // todo: confirm
削除しますか？のアラートは出してあげたい

2020-11-05 16:37 UTC, koogawa commented on src/repository/firebase.ts
> +  delete(eventId: string, commentId: string, userIdHashed: string): Promise<boolean> {
このへんで コメントIDとユーザーIDを比較する？

2020-11-05 18:38 UTC, mather commented
@koogawa フロントから API を呼び出すかどうかの判定にしてしまうと誰でもコールできてしまうので、 functions で判定する必要がありますね。
`commentId` から既存のコメントを取得し、 POST body に記載された生の `userId` をハッシュ化したものがコメントの `userIdHashed` と一致した場合削除、そうでない場合は 403 という感じかな。

2020-11-06 00:35 UTC, koogawa commented
@mather なるほど、ありがとうございます！その方式で進めてみます

2020-11-06 02:29 UTC, mather requested changes
少しコメントしました。

2020-11-06 02:29 UTC, mather commented on src/components/CommentBlock.vue
> +    const delComment = () => {
個人的に省略形があまり好きではないので、 `deleteMyComment` などにしておきたい気持ちがあります。

2020-11-06 02:34 UTC, koogawa commented on src/components/CommentBlock.vue
> +    const delComment = () => {
@mather  `deleteMyComment ` 良いですね！変更します

ここは deleteComment が使えなかったので、悩んだ末に delComment にしたんですが、自分もモヤッとしてました。
ありがとうございます 👍

2020-11-06 04:02 UTC, koogawa commented on src/components/CommentBlock.vue
> +    const delComment = () => {
:done: https://github.com/tegehoge/LeacTion/pull/34/commits/1d6c748331f0a7feb55306d8986dbc3b2256bf10

2020-11-06 13:40 UTC, koogawa commented
@mather 削除リクエストにコメントIDとハッシュ化前のユーザーIDを送って、function側で自分のコメントかどうか判別するようにしてみました

2020-11-08 02:22 UTC, mather commented
@koogawa `functions/` 以下で `npm install` したときの `package-lock.json` の差分も追加をお願いします。

2020-11-08 03:32 UTC, koogawa commented
@mather package-lock.json の差分も追加しました 🙏 
https://github.com/tegehoge/LeacTion/pull/34/commits/cc52b60186c8a970de9440343a882ecf7efd8c5b

2020-11-08 04:03 UTC, mather approved these changes
LGTM!

2020-11-08 07:55 UTC, koogawa commented
レビューありがとうございました！

2020-11-08 09:11 UTC, merged