[update] トップページのデザイン
tegehoge/LeacTion pull request #44
Opened 2020-11-22 03:00 UTC by tomoeine

## チケット
https://github.com/tegehoge/LeacTion/issues/7

## やったこと
トップページにいろいろ文章を書いてレイアウトを調整した。1個だけ画像も追加。

## 見て欲しいこと
文章もデザインも個人の感覚で頑張ってみただけなので、「もっとこうしたい」とかガンガンご意見ください〜

2020-11-23 07:40 UTC, mather requested changes
デザインと文言を確認しました。最高です！
一箇所だけ `yarn build` 時にエラーが起こってたので、修正をお願いします。

2020-11-23 07:40 UTC, mather commented on src/pages/Top.vue
> +      <img src="images/baloon.png" class="w-24 mb-3 mx-auto" />
相対パスでも動くのですが、 `/images/baloon.png` にしたほうが良いと思います。
( `yarn build` で出ているエラーの解消 )

2020-11-24 00:09 UTC, tomoeine commented on src/pages/Top.vue
> +      <img src="images/baloon.png" class="w-24 mb-3 mx-auto" />
あああ yarn build で怒られてるの気づかず、すみません・・・
直しました！

2020-11-24 04:27 UTC, mather approved these changes

2020-11-24 04:27 UTC, merged